import logging
import re
from typing import Dict, Any

from app.ai.state import LoanAssessmentState

logger = logging.getLogger(__name__)


def extract_features_from_message(message_content: str) -> Dict[str, Any]:
    """
    Extract Home Credit features from user message via natural language parsing.

    Maps natural language descriptions to Home Credit dataset column names
    (128-feature XGBoost model). Derived ratios are computed automatically.

    Args:
        message_content: The user's message text

    Returns:
        Dictionary of extracted features using Home Credit column names
    """
    features = {}
    content_lower = message_content.lower()

    # --- Age → DAYS_BIRTH (negative days) ---
    for pattern in [r'age[:\s]+(\d+)', r'(\d+)\s*years?\s*old']:
        match = re.search(pattern, content_lower)
        if match:
            age = float(match.group(1))
            features['DAYS_BIRTH'] = -age * 365.25
            break

    # --- Income → AMT_INCOME_TOTAL ---
    for pattern in [
        r'income[:\s]+\$?([\d,]+)',
        r'earn[s]?\s+\$?([\d,]+)',
        r'salary[:\s]+\$?([\d,]+)',
        r'revenue[:\s]+\$?([\d,]+)',
    ]:
        match = re.search(pattern, content_lower)
        if match:
            features['AMT_INCOME_TOTAL'] = float(match.group(1).replace(',', ''))
            break

    # --- Loan amount → AMT_CREDIT ---
    for pattern in [
        r'loan[:\s]+\$?([\d,]+)',
        r'\$([\d,]+)\s*loan',
        r'credit[:\s]+\$?([\d,]+)',
        r'borrow[:\s]+\$?([\d,]+)',
    ]:
        match = re.search(pattern, content_lower)
        if match:
            features['AMT_CREDIT'] = float(match.group(1).replace(',', ''))
            break

    # --- Monthly payment → AMT_ANNUITY ---
    for pattern in [
        r'(?:monthly\s*)?(?:payment|annuity|installment)[:\s]+\$?([\d,]+)',
    ]:
        match = re.search(pattern, content_lower)
        if match:
            features['AMT_ANNUITY'] = float(match.group(1).replace(',', ''))
            break

    # --- Goods price → AMT_GOODS_PRICE ---
    for pattern in [
        r'(?:goods?\s*)?price[:\s]+\$?([\d,]+)',
        r'purchase[:\s]+\$?([\d,]+)',
    ]:
        match = re.search(pattern, content_lower)
        if match:
            features['AMT_GOODS_PRICE'] = float(match.group(1).replace(',', ''))
            break

    # --- Employment → DAYS_EMPLOYED (negative days) ---
    for pattern in [
        r'employed[:\s]+(\d+(?:\.\d+)?)\s*years?',
        r'(\d+(?:\.\d+)?)\s*years?\s*(?:of\s*)?employment',
        r'working[:\s]+(\d+(?:\.\d+)?)\s*years?',
    ]:
        match = re.search(pattern, content_lower)
        if match:
            years = float(match.group(1))
            features['DAYS_EMPLOYED'] = -years * 365.25
            break

    # --- Children → CNT_CHILDREN ---
    match = re.search(r'(\d+)\s*child(?:ren)?', content_lower)
    if match:
        features['CNT_CHILDREN'] = float(match.group(1))

    # --- Family members → CNT_FAM_MEMBERS ---
    match = re.search(r'(\d+)\s*family\s*members?', content_lower)
    if match:
        features['CNT_FAM_MEMBERS'] = float(match.group(1))

    # --- Compute derived ratios if base fields present ---
    if 'AMT_CREDIT' in features and 'AMT_INCOME_TOTAL' in features:
        features['credit_income_ratio'] = features['AMT_CREDIT'] / (features['AMT_INCOME_TOTAL'] + 1)
    if 'AMT_ANNUITY' in features and 'AMT_INCOME_TOTAL' in features:
        features['annuity_income_ratio'] = features['AMT_ANNUITY'] / (features['AMT_INCOME_TOTAL'] + 1)

    return features


async def credit_scoring_node(
    state: LoanAssessmentState,
    llm,
    tools: list
) -> Dict[str, Any]:
    """
    Node: Credit Scoring

    Dedicated node for running the XGBoost credit score model.
    Credit score must NEVER be generated by the LLM — only by this node.

    Args:
        state: Current loan assessment state
        llm: ChatAnthropic LLM instance (not used, but kept for consistency)
        tools: List of available tools

    Returns:
        Updated state with credit score and risk level
    """
    logger.info("⚙️ Running credit score model (XGBoost)...")

    # Find credit score model tool
    credit_model = next((t for t in tools if t.name == "credit_score_model"), None)

    if not credit_model:
        logger.warning("⚠️ credit_score_model tool not available — skipping")
        return state

    # Try to get features from state first (set by data_completeness_node)
    features = state.get("extracted_fields", {})

    # If not in state, extract from message as fallback
    if not features:
        logger.info("   No extracted_fields in state, extracting from message...")
        messages = state.get("messages", [])

        # Handle both string and list (multimodal) content
        if messages:
            content = messages[-1].content
            if isinstance(content, list):
                # Extract text from multimodal content
                last_message = " ".join([part.get("text", "") for part in content if part.get("type") == "text"])
            else:
                last_message = content
        else:
            last_message = ""

        features = extract_features_from_message(last_message)

    if not features:
        logger.warning("⚠️ No financial features found — cannot compute credit score")
        return state

    logger.info(f"   Using features: {features}")
    logger.info("   Computing default probability...")

    try:
        # Call the credit score model (wrap in applicant_data per tool schema)
        result = await credit_model.ainvoke({"applicant_data": features})

        credit_score = result.get("credit_score", 0)
        default_probability = result.get("default_probability", 0.0)
        score_band = result.get("score_band", "unknown")
        confidence = result.get("confidence", 0.0)
        recommendation = result.get("recommendation", "")

        # Map score to risk level
        if credit_score >= 800:
            risk_level = "low"
        elif credit_score >= 670:
            risk_level = "low"
        elif credit_score >= 580:
            risk_level = "medium"
        else:
            risk_level = "high"

        decision = "AUTO-APPROVE" if credit_score >= 800 else "APPROVE (with conditions)" if credit_score >= 670 else "MANUAL REVIEW" if credit_score >= 580 else "DECLINE"

        logger.info(f"   ✅ Score computed: {credit_score} ({score_band})")
        logger.info(f"   Default probability: {default_probability:.2%}")
        logger.info(f"   Risk level: {risk_level}")

        # Inject credit score as a message so downstream LLM nodes can see it
        from langchain_core.messages import AIMessage
        score_message = AIMessage(content=(
            f"**[XGBoost ML Model Result]**\n"
            f"- Credence Credit Score: **{credit_score}/850** ({score_band})\n"
            f"- Default Probability: **{default_probability:.1%}**\n"
            f"- Risk Level: **{risk_level.upper()}**\n"
            f"- Lending Decision: **{decision}**\n"
            f"- Model: XGBoost (Home Credit, 128 features)\n"
            f"- Features Provided: {result.get('features_provided', 0)}/{result.get('features_total', 128)}\n\n"
            f"This is the official credit score. Use this score in your analysis and report."
        ))

        # Update analysis steps
        analysis_steps = state.get("analysis_steps", [])
        analysis_steps.append(
            f"Credit scoring: {credit_score} ({score_band}), "
            f"default probability: {default_probability:.2%}, "
            f"risk: {risk_level}"
        )

        return {
            **state,
            "credit_score": credit_score,
            "default_probability": default_probability,
            "risk_level": risk_level,
            "analysis_steps": analysis_steps,
            "messages": list(state.get("messages", [])) + [score_message],
        }

    except Exception as e:
        logger.error(f" Error running credit score model: {str(e)}")
        return state
