import logging
import re
from typing import Dict, Any

from app.ai.state import LoanAssessmentState

logger = logging.getLogger(__name__)


def extract_features_from_message(message_content: str) -> Dict[str, Any]:
    """
    Extract financial features from user message using simple pattern matching.

    Args:
        message_content: The user's message text

    Returns:
        Dictionary of extracted features
    """
    features = {}
    content_lower = message_content.lower()

    # Extract loan amount
    loan_patterns = [
        r'loan.*?(\d+(?:,\d{3})*(?:\.\d+)?)\s*(?:million|m|vnd|k|thousand)',
        r'\$?\s*(\d+(?:,\d{3})*(?:\.\d+)?)\s*(?:million|m)\s*(?:loan|vnd)?',
        r'(\d+(?:,\d{3})*)\s*(?:vnd|k)\s*loan'
    ]
    for pattern in loan_patterns:
        match = re.search(pattern, content_lower)
        if match:
            amount_str = match.group(1).replace(',', '')
            # Convert to actual number
            if 'million' in message_content.lower() or 'm' in match.group(0):
                features['loan_amount'] = float(amount_str) * 1_000_000
            elif 'k' in match.group(0) or 'thousand' in message_content.lower():
                features['loan_amount'] = float(amount_str) * 1_000
            else:
                features['loan_amount'] = float(amount_str)
            break

    # Extract revenue
    revenue_patterns = [
        r'revenue.*?(\d+(?:,\d{3})*(?:\.\d+)?)\s*(?:million|m|vnd|k)',
        r'(\d+(?:,\d{3})*(?:\.\d+)?)\s*(?:million|m).*?revenue'
    ]
    for pattern in revenue_patterns:
        match = re.search(pattern, content_lower)
        if match:
            amount_str = match.group(1).replace(',', '')
            if 'million' in match.group(0) or 'm' in match.group(0):
                features['monthly_revenue'] = float(amount_str) * 1_000_000
            elif 'k' in match.group(0):
                features['monthly_revenue'] = float(amount_str) * 1_000
            else:
                features['monthly_revenue'] = float(amount_str)
            break

    # Extract business tenure
    tenure_patterns = [
        r'(\d+)\s*(?:years?|yrs?)\s*old',
        r'(?:tenure|operating for).*?(\d+)\s*(?:years?|months?)'
    ]
    for pattern in tenure_patterns:
        match = re.search(pattern, content_lower)
        if match:
            if 'month' in match.group(0):
                features['business_tenure_months'] = int(match.group(1))
            else:
                features['business_tenure_months'] = int(match.group(1)) * 12
            break

    # Extract profit margin
    margin_patterns = [
        r'(\d+(?:\.\d+)?)\s*%\s*(?:margin|profit)',
        r'margin.*?(\d+(?:\.\d+)?)\s*%'
    ]
    for pattern in margin_patterns:
        match = re.search(pattern, content_lower)
        if match:
            features['profit_margin'] = float(match.group(1)) / 100
            break

    # Extract industry (simple keyword matching)
    industries = ['retail', 'manufacturing', 'technology', 'services', 'agriculture', 'hospitality', 'construction']
    for industry in industries:
        if industry in content_lower:
            features['industry'] = industry
            break

    return features


async def credit_scoring_node(
    state: LoanAssessmentState,
    llm,
    tools: list
) -> Dict[str, Any]:
    """
    Node: Credit Scoring

    Dedicated node for running the XGBoost credit score model.
    Credit score must NEVER be generated by the LLM — only by this node.

    Args:
        state: Current loan assessment state
        llm: ChatAnthropic LLM instance (not used, but kept for consistency)
        tools: List of available tools

    Returns:
        Updated state with credit score and risk level
    """
    logger.info("⚙️ Running credit score model (XGBoost)...")

    # Find credit score model tool
    credit_model = next((t for t in tools if t.name == "credit_score_model"), None)

    if not credit_model:
        logger.warning("⚠️ credit_score_model tool not available — skipping")
        return state

    # Try to get features from state first (set by data_completeness_node)
    features = state.get("extracted_fields", {})

    # If not in state, extract from message as fallback
    if not features:
        logger.info("   No extracted_fields in state, extracting from message...")
        messages = state.get("messages", [])

        # Handle both string and list (multimodal) content
        if messages:
            content = messages[-1].content
            if isinstance(content, list):
                # Extract text from multimodal content
                last_message = " ".join([part.get("text", "") for part in content if part.get("type") == "text"])
            else:
                last_message = content
        else:
            last_message = ""

        features = extract_features_from_message(last_message)

    if not features:
        logger.warning("⚠️ No financial features found — cannot compute credit score")
        return state

    logger.info(f"   Using features: {features}")
    logger.info("   Computing default probability...")

    try:
        # Call the credit score model
        result = await credit_model.ainvoke(features)

        credit_score = result.get("credit_score", 0)
        default_probability = result.get("default_probability", 0.0)
        score_band = result.get("score_band", "unknown")
        confidence = result.get("confidence", 0.0)
        recommendation = result.get("recommendation", "")

        # Map score to risk level
        if credit_score >= 800:
            risk_level = "low"
        elif credit_score >= 670:
            risk_level = "low"
        elif credit_score >= 580:
            risk_level = "medium"
        else:
            risk_level = "high"

        logger.info(f"   ✅ Score computed: {credit_score} ({score_band})")
        logger.info(f"   Default probability: {default_probability:.2%}")
        logger.info(f"   Risk level: {risk_level}")

        # Update analysis steps
        analysis_steps = state.get("analysis_steps", [])
        analysis_steps.append(
            f"Credit scoring: {credit_score} ({score_band}), "
            f"default probability: {default_probability:.2%}, "
            f"risk: {risk_level}"
        )

        return {
            **state,
            "credit_score": credit_score,
            "default_probability": default_probability,
            "risk_level": risk_level,
            "analysis_steps": analysis_steps,
        }

    except Exception as e:
        logger.error(f"❌ Error running credit score model: {str(e)}")
        return state
